/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TaskOpenDescription {
        /**
          * The Description of the Task
         */
        "description": string;
        /**
          * The due Date
         */
        "dueDate": string;
        /**
          * Notes on the Task
         */
        "note": string;
    }
}
declare global {
    interface HTMLTaskOpenDescriptionElement extends Components.TaskOpenDescription, HTMLStencilElement {
    }
    var HTMLTaskOpenDescriptionElement: {
        prototype: HTMLTaskOpenDescriptionElement;
        new (): HTMLTaskOpenDescriptionElement;
    };
    interface HTMLElementTagNameMap {
        "task-open-description": HTMLTaskOpenDescriptionElement;
    }
}
declare namespace LocalJSX {
    interface TaskOpenDescription {
        /**
          * The Description of the Task
         */
        "description"?: string;
        /**
          * The due Date
         */
        "dueDate"?: string;
        /**
          * Notes on the Task
         */
        "note"?: string;
    }
    interface IntrinsicElements {
        "task-open-description": TaskOpenDescription;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "task-open-description": LocalJSX.TaskOpenDescription & JSXBase.HTMLAttributes<HTMLTaskOpenDescriptionElement>;
        }
    }
}
